import fs from "fs";
import path from "path";

export function generateReport({ url, status, headersReport }) {
  const date = new Date().toISOString().split("T")[0];
  const hostname = new URL(url).hostname.replace(/\./g, "_");

  const fileName = `report_${hostname}_${date}.md`;
  const reportsDir = path.resolve("reports");
  const filePath = path.join(reportsDir, fileName);

  const content = `
# Website Audit Report 🛠️

**Website:** ${url}  
**Date:** ${date}  
**HTTP Status:** ${status}

---

## 🔐 Security Headers Audit

${headersReport.map(line => `- ${line}`).join("\n")}

---

## ℹ️ Notes

- This audit is **passive** and analyzes only publicly available information.
- No attacks or exploitation techniques were used.
- This report is intended to help improve the website.

---

Generated by **Site Helper**
`;

  fs.writeFileSync(filePath, content.trim());
  return filePath;
}

